Traceback (most recent call last):
  File "C:\Users\ShaileshShrestha\anaconda3\envs\myenv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\ShaileshShrestha\anaconda3\envs\myenv\lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\ShaileshShrestha\anaconda3\envs\myenv\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\ShaileshShrestha\anaconda3\envs\myenv\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\ShaileshShrestha\anaconda3\envs\myenv\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ShaileshShrestha\anaconda3\envs\myenv\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ShaileshShrestha\anaconda3\envs\myenv\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import netCDF4 as nc

# Open the NetCDF file in read mode
dataset = nc.Dataset(filepath, mode='r')

# List all variables in the dataset
variables_list = dataset.variables.keys()
print(f"Available variables: {list(variables_list)}")

# Extract coordinate data and the primary variable's data
lon_list = dataset['longitude'][:]  # Extract longitude
lat_list = dataset['latitude'][:]  # Extract latitude
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[3], line 4[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mnetCDF4[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mnc[39;00m
[0;32m      3[0m [38;5;66;03m# Open the NetCDF file in read mode[39;00m
[1;32m----> 4[0m dataset [38;5;241m=[39m [43mnc[49m[38;5;241;43m.[39;49m[43mDataset[49m[43m([49m[43mfilepath[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m      6[0m [38;5;66;03m# List all variables in the dataset[39;00m
[0;32m      7[0m variables_list [38;5;241m=[39m dataset[38;5;241m.[39mvariables[38;5;241m.[39mkeys()

File [1;32msrc\\netCDF4\\_netCDF4.pyx:2521[0m, in [0;36mnetCDF4._netCDF4.Dataset.__init__[1;34m()[0m

File [1;32msrc\\netCDF4\\_netCDF4.pyx:2158[0m, in [0;36mnetCDF4._netCDF4._ensure_nc_success[1;34m()[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '.\\data\\era5-land-monthly\\download\\reanalysis-era5-land-monthly-means_2m_temperature_1950_2024.nc'

