Traceback (most recent call last):
  File "F:\_str.ucture\CoKLIMAx (Phase2)\CoKLIMAx-II\cds_venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "F:\_str.ucture\CoKLIMAx (Phase2)\CoKLIMAx-II\cds_venv\lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "F:\_str.ucture\CoKLIMAx (Phase2)\CoKLIMAx-II\cds_venv\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\Shailesh\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "F:\_str.ucture\CoKLIMAx (Phase2)\CoKLIMAx-II\cds_venv\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "F:\_str.ucture\CoKLIMAx (Phase2)\CoKLIMAx-II\cds_venv\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "F:\_str.ucture\CoKLIMAx (Phase2)\CoKLIMAx-II\cds_venv\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import json
from landsatxplore.api import API

# Load credentials from a local JSON file
with open("G:/usgs.json", "r") as file:
    credentials = json.load(file)

username = credentials["username"]
password = credentials["password"]
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[2], line 2[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mjson[39;00m
[1;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mlandsatxplore[39;00m[38;5;21;01m.[39;00m[38;5;21;01mapi[39;00m [38;5;28;01mimport[39;00m API
[0;32m      4[0m [38;5;66;03m# Load credentials from a local JSON file[39;00m
[0;32m      5[0m [38;5;28;01mwith[39;00m [38;5;28mopen[39m([38;5;124m"[39m[38;5;124mG:/usgs.json[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mr[39m[38;5;124m"[39m) [38;5;28;01mas[39;00m file:

[1;31mModuleNotFoundError[0m: No module named 'landsatxplore'

